name: Test and (if new tag) deploy to PyPI

on: push

jobs:
  build-n-publish:
    name: Publish package to PyPI and TestPyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    # TODO dependencies cache
    - name: Install package and dependencies
      run: |
        python -m pip install wheel pytest
        python -m pip install .
    - name: Run pytest
      run: python -m pytest -s tests
    - name: Build a binary wheel and a source tarball
      run: python setup.py sdist bdist_wheel --universal
    - name: Publish package to Test PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
    # logic of this action is to upload when something is tagged - it is uploaded to pypi.
    # version, however, is still defined by code, not github tag
    - name: Publish package to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}